from bridg/java8
run mkdir /jars
copy /target/noteserviceapp-0.0.1-SNAPSHOT.jar /jars/noteserviceapp-0.0.1-SNAPSHOT.jar
expose 8081:8081
cmd ["java","-jar","/jars/noteserviceapp-0.0.1-SNAPSHOT.jar"]